# Requête vers /api/links
POST http://localhost:3000/api/links
Content-Type: application/json

{
  "title": "Google",
  "url": "https://google.com",
  "icon": "🔍"
}

###

# Requête vers /api/links
POST http://localhost:3000/api/links
Content-Type: application/json

{
  "title": "Youtube",
  "url": "https://youtube.com",
  "icon": "🔍"
}

###

# Requête vers /api/links
POST http://localhost:3000/api/links
Content-Type: application/json

{
  "title": "twitter",
  "url": "https://x.com",
  "icon": "🔍"
}

###

# Test PATCH /api/links/reorder
PATCH http://localhost:3000/api/links/reorder
Content-Type: application/json

[
  {
    "id": "1774350879845",
    "title": "Google",
    "url": "https://google.com",
    "icon": "🔍",
    "order": 3,
    "active": true,
    "createdAt": "2026-03-24T11:14:39.845Z"
  },
  {
    "id": "1774350995425",
    "title": "Google",
    "url": "https://google.com",
    "icon": "🔍",
    "order": 12,
    "active": true,
    "createdAt": "2026-03-24T11:16:35.425Z"
  },
  {
    "id": "1774351001848",
    "title": "Youtube",
    "url": "https://youtube.com",
    "icon": "🔍",
    "order": 7,
    "active": true,
    "createdAt": "2026-03-24T11:16:41.848Z"
  }
]